version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./auth
    expose:
      - "5001"

  profile:
    build: ./profile
    expose:
      - "5002"

  cart:
    build: ./cart
    expose:
      - "5003"
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  orders:
    build: ./orders
    expose:
      - "5005"
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - cart

  payment:
    build: ./payment
    expose:
      - "5004"
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - orders

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - profile
      - cart
      - orders
      - payment
